name: Build Python EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11' 
        
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    
    - name: Install cx_Freeze
      run: pip install cx_Freeze
    
    - name: Install pywin32
      run: |
        pip install pywin32
        PYWIN32_PATH=$(python -c "import site; print(site.getsitepackages()[0])")
        python "$PYWIN32_PATH/pywin32_postinstall.py" -install
      shell: bash
        
    - name: Build EXE
      run: |
        dir
        python build-dd2as.py build
      working-directory: ${{ github.workspace }}
        
    # - name: Zip build directory
    #   run: |
    #     7z a DD2AutoSlider.zip ${{ github.workspace }}\build\DD2AutoSlider\*
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DD2AutoSlider
        path: ${{ github.workspace }}\build\DD2AutoSlider
